# Generated by Django 2.1.1 on 2018-09-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRealTimeTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol_tree', models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('USDT', 'USDT')], max_length=64)),
                ('best_ask_pr', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('best_ask_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('best_bid_pr', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('best_bid_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('pr_change', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('pr_change_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_pr_close', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('last_trade_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('high_pr_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('low_pr_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('cross_symbols', models.ManyToManyField(blank=True, related_name='_allrealtimeticker_cross_symbols_+', to='info_data.AllRealTimeTicker')),
            ],
        ),
    ]
