# Generated by Django 2.1.1 on 2018-09-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='best_ask_pr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='best_ask_qty',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='best_bid_pr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='best_bid_qty',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='high_pr_24h',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='last_pr_close',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='last_trade_qty',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='low_pr_24h',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='allrealtimeticker',
            name='pr_change',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
    ]
