# Generated by Django 2.1.1 on 2018-09-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0002_auto_20180912_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrealtimeticker',
            name='cross_symbols',
        ),
    ]
