# Generated by Django 2.1.1 on 2018-09-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20180912_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('stop_qty', models.IntegerField(blank=True, null=True)),
                ('switch_trading', models.BooleanField(default=False)),
                ('binance_api', models.ManyToManyField(blank=True, to='profiles.BinanceKey')),
                ('telegram_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.TelegramBotSettings')),
            ],
        ),
        migrations.CreateModel(
            name='ClosedDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_base_pair', models.DateTimeField(auto_now_add=True)),
                ('datetime_middle_pair', models.DateTimeField(blank=True, null=True)),
                ('datetime_end_pair', models.DateTimeField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=8, max_digits=25)),
                ('middle_price', models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True)),
                ('end_price', models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True)),
                ('base_qty', models.DecimalField(decimal_places=8, max_digits=25)),
                ('middle_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True)),
                ('end_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True)),
                ('base_pair', models.CharField(max_length=16)),
                ('middle_pair', models.CharField(max_length=16)),
                ('end_pair', models.CharField(max_length=16)),
                ('invest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_roi', models.DecimalField(decimal_places=2, max_digits=3)),
                ('expected_profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OpenedDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pair', models.CharField(max_length=16)),
                ('middle_pair', models.CharField(max_length=16)),
                ('end_pair', models.CharField(max_length=16)),
                ('date_open', models.DateTimeField(auto_now_add=True)),
                ('base_qty', models.DecimalField(decimal_places=8, max_digits=25)),
                ('middle_qty', models.DecimalField(decimal_places=8, max_digits=25)),
                ('end_qty', models.DecimalField(decimal_places=8, max_digits=25)),
                ('base_price', models.DecimalField(decimal_places=8, max_digits=25)),
                ('middle_price', models.DecimalField(decimal_places=8, max_digits=25)),
                ('end_price', models.DecimalField(decimal_places=8, max_digits=25)),
                ('base_order_id', models.CharField(blank=True, max_length=32, null=True)),
                ('middle_order_id', models.CharField(blank=True, max_length=32, null=True)),
                ('end_order_id', models.CharField(blank=True, max_length=32, null=True)),
                ('is_base_order_set', models.BooleanField(default=False)),
                ('is_middle_order_set', models.BooleanField(default=False)),
                ('is_end_order_set', models.BooleanField(default=False)),
                ('is_base_order_filled', models.BooleanField(default=False)),
                ('is_middle_order_filled', models.BooleanField(default=False)),
                ('is_end_order_filled', models.BooleanField(default=False)),
                ('invest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_roi', models.DecimalField(decimal_places=2, max_digits=3)),
                ('expected_profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
