# Generated by Django 2.1.1 on 2018-09-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180912_1740'),
        ('arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='binance_api',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='binance_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.BinanceKey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='telegram_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.TelegramBotSettings'),
            preserve_default=False,
        ),
    ]
