# Generated by Django 2.1.1 on 2018-09-22 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0003_auto_20180920_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='profit_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6),
        ),
    ]
