# Generated by Django 2.1.1 on 2018-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0004_botsettings_profit_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeddeals',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
