# Generated by Django 2.1.1 on 2018-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0005_closeddeals_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeddeals',
            name='expected_profit',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='closeddeals',
            name='expected_return',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='closeddeals',
            name='invest_amount',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='closeddeals',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='closeddeals',
            name='return_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
