# Generated by Django 2.1.1 on 2018-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0007_auto_20180923_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='base_qty',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='end_qty',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='invest_amount',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='middle_qty',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='real_end_price',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='real_middle_price',
        ),
        migrations.AddField(
            model_name='deals',
            name='end_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='expected_base_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deals',
            name='expected_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deals',
            name='expected_invest',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deals',
            name='init_qty',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deals',
            name='invest',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='is_traded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deals',
            name='middle_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='transit_qty',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='return_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=25, null=True),
        ),
    ]
