# Generated by Django 2.1.1 on 2018-09-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0008_auto_20180925_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='expected_fee',
        ),
    ]
